### ISSUE TITLE
WorkMode in Klartext ausgeben

### ISSUE THREAD

**Issue by OstfrieseUnterwegs** [Smart-Gang/ioBroker.linktap#2]
Der WorkMode könnte als Klartext ausgegeben werden. Dazu den Common Block erweitern um

    "states": {
      "O": "Odd-Even Mode",
      "M": "Instant Mode",
      "I": "Interval Mode",
      "T": "7-Day Mode",
      "Y": "Month Mode",
      "N": "Mode not set"
    }

**Comment by Smart-Gang** [comment]
Ist im Release 0.1.8 implementiert. 
Bitte [hier](https://forum.iobroker.net/topic/43794/test-adapter-linktap-v-0-1-8-github) testen.
Danke
