### ISSUE TITLE
1. Start on new day does not start the watering ?

### ISSUE THREAD

**Issue by Starter4711** [Smart-Gang/ioBroker.linktap#3]
**Describe the bug**  
First start via instant mode does not start watering.
Start out of Blockly, command shown in Log.

V0.1.8
ioBroker up to date. 3.2.16 v12.22.1 6.14.12
[linktap.pdf](https://github.com/Smart-Gang/ioBroker.linktap/files/6667550/linktap.pdf)

Log, polling, Start instand at 7:00, after it did not work, chanched the adapter to debug mode, then it worked (2.).

**Comment by Smart-Gang** [comment]
Thanks for reporting.

At first glance, the logs do not show any error behavior. At 7 o'clock the StartInstantMode button is triggered. I can see here that the runtime is specified for 5 minutes. The command also goes out and is successfully responded with HTTP 200 from the LinkTap web service.
Now, as with the app, it can always take a while for the irrigation to start. In the app 15 seconds are described. 
Did nothing happen with you in the minute before you run the StopInstantMode command?
Is it reproducible? I basically do the same as you and have built a logic with Javascript (instead of Blockly), where I can then start the irrigation via Alexa or sensor-controlled. 
Do you have Discord or another messenger where we can discuss this in more detail?

**Comment by Starter4711** [comment]
Hi,
same today, log shows start, nothing happens
Restart of Adapter and stop start , it works again.
Discord, Slack, Signal, Telegram as you like, via PN?
[linktap.pdf](https://github.com/Smart-Gang/ioBroker.linktap/files/6674883/linktap.pdf)

**Comment by Starter4711** [comment]
Just made a test, did not work.
simplest Blockly, log shows on and off, nothing happend.
`
<img width="850" alt="Bildschirmfoto 2021-06-18 um 08 47 51" src="https://user-images.githubusercontent.com/15359915/122518771-eb8f7180-d011-11eb-8de2-0c75cd2a61fd.png">

2021-06-18 08:45:52.987 -&nbsp;info: linktap.0 (71277) updateWateringStatus started
--
2021-06-18 08:45:53.632 -&nbsp;info: linktap.0 (71277) Queried watering status for device TapLinker. Status: 200
2021-06-18 08:45:53.633 -&nbsp;info: linktap.0 (71277) updateWateringStatus finished
2021-06-18 08:46:00.015 -&nbsp;info: javascript.0 (1041) script.js.common.Skript_1: Bewässerung gestartet
2021-06-18 08:46:00.108 -&nbsp;info: linktap.0 (71277) state linktap.0.03444023004B1200.13414023004B1200.StartInstantMode changed: true (ack = false)
2021-06-18 08:46:00.553 -&nbsp;info: linktap.0 (71277) Sent instant mode command with action: true and duration: 5. Status: 200
2021-06-18 08:46:30.016 -&nbsp;info: linktap.0 (71277) state linktap.0.03444023004B1200.13414023004B1200.StopInstantMode changed: true (ack = false)
2021-06-18 08:46:30.622 -&nbsp;info: linktap.0 (71277) Sent instant mode command with action: false and duration: 0. Status: 200

`

**Comment by Smart-Gang** [comment]
There is no pm function in github.  So you can contact me in Discord: Gangrulez
1743
Pls contact me. Thank you.

I created a test script to verify the states for a duration of 5 minutes. Are you able to run it?

var startInstantModeButton = "linktap.0.03444023004B1200.13414023004B1200.StartInstantMode";

var stopInstantModeButton = startInstantModeButton.replace("StartInstantMode", "StopInstantMode");
var instantModeDuration = startInstantModeButton.replace("StartInstantMode", "InstantModeDuration");

var taplinkerStatus = startInstantModeButton.replace("StartInstantMode", "status");
var taplinkerWatering = startInstantModeButton.replace("StartInstantMode", "watering");
var taplinkerBattery = startInstantModeButton.replace("StartInstantMode", "batteryStatus");
var taplinkerSignal = startInstantModeButton.replace("StartInstantMode", "signal");
var taplinkerNoWater = startInstantModeButton.replace("StartInstantMode", "noWater");
var taplinkerOnDuration = startInstantModeButton.replace("StartInstantMode", "onDuration");
var taplinkerVol = startInstantModeButton.replace("StartInstantMode", "vol");
var taplinkerVel = startInstantModeButton.replace("StartInstantMode", "vel");
var taplinkerTotal = startInstantModeButton.replace("StartInstantMode", "total");
var intervalCounter = 0;

function WriteIrrigationTestLog(){
    console.log("State: "+getState(taplinkerStatus).val 
        +" - Battery: "+getState(taplinkerBattery).val 
        +" - Signal: "+getState(taplinkerSignal).val 
        +" - Watering: "+getState(taplinkerWatering).val
        +" - noWater: "+getState(taplinkerNoWater).val
        +" - onDuration: "+getState(taplinkerOnDuration).val
        +" - vol: "+getState(taplinkerVol).val
        +" - vel: "+getState(taplinkerVel).val
        +" - total: "+getState(taplinkerTotal).val
        +" - instantModeDuration: "+getState(instantModeDuration).val        
        );
}
function setWateringState2(min) {        
    setState(instantModeDuration, min);
    setState(startInstantModeButton, true);  

    var intervalID = setInterval(function () {
        WriteIrrigationTestLog();
        if (++intervalCounter === 5) {
            clearInterval(intervalID);
        }        
    }, 60000);   
}
console.log("Start");
WriteIrrigationTestLog();
setWateringState2(5);

**Comment by Starter4711** [comment]
Hi, could not send you a message on Discord(blocked), sent friend request.
Are you German? my motherlanguage is german.

Tried your scripts, immediately it switches on and about 5min off. 
Log does not show values, because actually the watering is disabled, need to cut the lawn. Friends are comming today ;)
`

07:25:37.937 | info | javascript.0 (1041) Stop script script.js.common.Testscript_LinkTap
-- | -- | --
09:31:12.691 | info | javascript.0 (1041) Start javascript script.js.common.Testscript_LinkTap
09:31:12.708 | info | javascript.0 (1041) script.js.common.Testscript_LinkTap: Start
09:31:12.709 | info | javascript.0 (1041) script.js.common.Testscript_LinkTap: State: Connected - Battery: 94 - Signal: 79 - Watering: false - noWater: false - onDuration: 0 - vol: 0 - vel: 0 - total: 0 - instantModeDuration: 5
09:31:12.709 | info | javascript.0 (1041) script.js.common.Testscript_LinkTap: registered 0 subscriptions and 0 schedules
09:32:12.710 | info | javascript.0 (1041) script.js.common.Testscript_LinkTap: State: Connected - Battery: 94 - Signal: 79 - Watering: true - noWater: false - onDuration: 5 - vol: 0 - vel: 0 - total: 5 - instantModeDuration: 5
09:33:12.710 | info | javascript.0 (1041) script.js.common.Testscript_LinkTap: State: Connected - Battery: 94 - Signal: 79 - Watering: true - noWater: false - onDuration: 4 - vol: 0 - vel: 0 - total: 5 - instantModeDuration: 5
09:34:12.709 | info | javascript.0 (1041) script.js.common.Testscript_LinkTap: State: Connected - Battery: 94 - Signal: 79 - Watering: true - noWater: false - onDuration: 3 - vol: 0 - vel: 0 - total: 5 - instantModeDuration: 5
09:35:12.709 | info | javascript.0 (1041) script.js.common.Testscript_LinkTap: State: Connected - Battery: 94 - Signal: 79 - Watering: true - noWater: false - onDuration: 2 - vol: 0 - vel: 0 - total: 5 - instantModeDuration: 5
09:36:12.710 | info | javascript.0 (1041) script.js.common.Testscript_LinkTap: State: Connected - Battery: 94 - Signal: 79 - Watering: true - noWater: false - onDuration: 1 - vol: 0 - vel: 0 - total: 5 - instantModeDuration: 5

`

**Comment by Smart-Gang** [comment]
Fixed by adding state to the buttons.
