### ISSUE TITLE
"Accumulated volume of running watering slot" bleibt immer bei 0 ml

### ISSUE THREAD

**Issue by joe050860** [Smart-Gang/ioBroker.linktap#4]
Wasserdurchlauf hat anscheint keine Funktion!?

**Comment by Smart-Gang** [comment]
Laut der Herstellerdokumentation der API erhält man die Werte nur für die Modelle G2 und G2S.
[https://www.link-tap.com/#!/api-for-developers](https://www.link-tap.com/#!/api-for-developers)

Zudem muss der Stecker vom Mengendurchflussmesser korrekt montiert sein. Erst dann erhält man für "vel" und "vol" Werte.
Ich habe den G2 und da werden die Werte korrekt übergeben. Bitte also einmal prüfen, ob das Gerät diese Funktion bietet und ob vel / vol überhaupt mit dem Mengendurchflussmesser korrekt funktioniert. Die App zeigt ja auch entsprechende Messwerte

**Comment by joe050860** [comment]
Ich habe eins dieser Modelle. Das Volumen wird auch innerhalb der history ausgewiesen. Also grundsätzlich registrierter das Volumen schon. Nur nicht beim Datenpunkt vol

**Comment by Smart-Gang** [comment]
OK, Zeigt der state "vel" denn Werte an, wenn die Bewässerung aktiv ist? Es dauert ggf. mal eine Minute (also ein Pollintervall) bis Werte kommen.
Was noch getestet werden könnte, wäre den Adapter einmal zu löschen und neu zu installieren, um sicherzugehen, dass die state Attribute korrekt konfiguriert sind. Es gab in einem der letzten beiden Updates Änderungen hierzu.

**Comment by joe050860** [comment]
Ich habe den Adapter neu installiert. vel zeigt sporadisch einen Wert an und dann springt watering auch auf true. Ich nehme an, der Fehler liegt dann nicht bei  deiner Programmierung, sondern bei Link-Tap.

**Comment by Smart-Gang** [comment]
Das Verhalten ist schon merkwürdig. Ich kann gerne mal via Discord oder einem anderem Tool gerne mal einen Blick darauf werfen.
